// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKYro21HnWoveiGvv-VQF7HOdMeDpBQX8',
    appId: '1:279404493521:web:cf0c51e4ba1dca155de3f0',
    messagingSenderId: '279404493521',
    projectId: 'medx-529ef',
    authDomain: 'medx-529ef.firebaseapp.com',
    storageBucket: 'medx-529ef.appspot.com',
    measurementId: 'G-SNBV3YE1P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByIBaiOU46r1KWMCjREY-0Rbd4YmCnWEY',
    appId: '1:279404493521:android:45eaaf5621c57caf5de3f0',
    messagingSenderId: '279404493521',
    projectId: 'medx-529ef',
    storageBucket: 'medx-529ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjYYIF81nAfojA6hVA--IdmztSuaRWRE',
    appId: '1:279404493521:ios:d141b158f7d0b66b5de3f0',
    messagingSenderId: '279404493521',
    projectId: 'medx-529ef',
    storageBucket: 'medx-529ef.appspot.com',
    iosBundleId: 'com.medx.app.medx',
  );
}
